CREATE TABLE IF NOT EXISTS players
(
    id    VARCHAR(64) PRIMARY KEY,
    red   BIGINT NOT NULL DEFAULT 0,
    green BIGINT NOT NULL DEFAULT 0,
    blue  BIGINT NOT NULL DEFAULT 0,
    nonce BIGINT NOT NULL DEFAULT 0
);
