// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/proto/v1/game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RewardColor int32

const (
	RewardColor_RED   RewardColor = 0
	RewardColor_GREEN RewardColor = 1
	RewardColor_BLUE  RewardColor = 2
)

// Enum value maps for RewardColor.
var (
	RewardColor_name = map[int32]string{
		0: "RED",
		1: "GREEN",
		2: "BLUE",
	}
	RewardColor_value = map[string]int32{
		"RED":   0,
		"GREEN": 1,
		"BLUE":  2,
	}
)

func (x RewardColor) Enum() *RewardColor {
	p := new(RewardColor)
	*p = x
	return p
}

func (x RewardColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RewardColor) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_game_proto_enumTypes[0].Descriptor()
}

func (RewardColor) Type() protoreflect.EnumType {
	return &file_api_proto_v1_game_proto_enumTypes[0]
}

func (x RewardColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RewardColor.Descriptor instead.
func (RewardColor) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{0}
}

type RequestMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMissionRequest) Reset() {
	*x = RequestMissionRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMissionRequest) ProtoMessage() {}

func (x *RequestMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMissionRequest.ProtoReflect.Descriptor instead.
func (*RequestMissionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMissionRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type MissionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MissionId       string                 `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	RewardColor     RewardColor            `protobuf:"varint,2,opt,name=reward_color,json=rewardColor,proto3,enum=rgb.ledger.v1.RewardColor" json:"reward_color,omitempty"`
	CooldownSeconds int32                  `protobuf:"varint,3,opt,name=cooldown_seconds,json=cooldownSeconds,proto3" json:"cooldown_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MissionResponse) Reset() {
	*x = MissionResponse{}
	mi := &file_api_proto_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionResponse) ProtoMessage() {}

func (x *MissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionResponse.ProtoReflect.Descriptor instead.
func (*MissionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *MissionResponse) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *MissionResponse) GetRewardColor() RewardColor {
	if x != nil {
		return x.RewardColor
	}
	return RewardColor_RED
}

func (x *MissionResponse) GetCooldownSeconds() int32 {
	if x != nil {
		return x.CooldownSeconds
	}
	return 0
}

type CompleteMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     string                 `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMissionRequest) Reset() {
	*x = CompleteMissionRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMissionRequest) ProtoMessage() {}

func (x *CompleteMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMissionRequest.ProtoReflect.Descriptor instead.
func (*CompleteMissionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteMissionRequest) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *CompleteMissionRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type CompleteMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	NewBalance    *BalanceResponse       `protobuf:"bytes,4,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMissionResponse) Reset() {
	*x = CompleteMissionResponse{}
	mi := &file_api_proto_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMissionResponse) ProtoMessage() {}

func (x *CompleteMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMissionResponse.ProtoReflect.Descriptor instead.
func (*CompleteMissionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteMissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteMissionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CompleteMissionResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *CompleteMissionResponse) GetNewBalance() *BalanceResponse {
	if x != nil {
		return x.NewBalance
	}
	return nil
}

var File_api_proto_v1_game_proto protoreflect.FileDescriptor

const file_api_proto_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/game.proto\x12\rrgb.ledger.v1\x1a\x19api/proto/v1/ledger.proto\"4\n" +
	"\x15RequestMissionRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\x9a\x01\n" +
	"\x0fMissionResponse\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\tR\tmissionId\x12=\n" +
	"\freward_color\x18\x02 \x01(\x0e2\x1a.rgb.ledger.v1.RewardColorR\vrewardColor\x12)\n" +
	"\x10cooldown_seconds\x18\x03 \x01(\x05R\x0fcooldownSeconds\"T\n" +
	"\x16CompleteMissionRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\tR\tmissionId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\xb2\x01\n" +
	"\x17CompleteMissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12?\n" +
	"\vnew_balance\x18\x04 \x01(\v2\x1e.rgb.ledger.v1.BalanceResponseR\n" +
	"newBalance*+\n" +
	"\vRewardColor\x12\a\n" +
	"\x03RED\x10\x00\x12\t\n" +
	"\x05GREEN\x10\x01\x12\b\n" +
	"\x04BLUE\x10\x022\xcb\x01\n" +
	"\vGameService\x12X\n" +
	"\x0eRequestMission\x12$.rgb.ledger.v1.RequestMissionRequest\x1a\x1e.rgb.ledger.v1.MissionResponse\"\x00\x12b\n" +
	"\x0fCompleteMission\x12%.rgb.ledger.v1.CompleteMissionRequest\x1a&.rgb.ledger.v1.CompleteMissionResponse\"\x00B\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_api_proto_v1_game_proto_rawDescOnce sync.Once
	file_api_proto_v1_game_proto_rawDescData []byte
)

func file_api_proto_v1_game_proto_rawDescGZIP() []byte {
	file_api_proto_v1_game_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_game_proto_rawDesc), len(file_api_proto_v1_game_proto_rawDesc)))
	})
	return file_api_proto_v1_game_proto_rawDescData
}

var file_api_proto_v1_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_game_proto_goTypes = []any{
	(RewardColor)(0),                // 0: rgb.ledger.v1.RewardColor
	(*RequestMissionRequest)(nil),   // 1: rgb.ledger.v1.RequestMissionRequest
	(*MissionResponse)(nil),         // 2: rgb.ledger.v1.MissionResponse
	(*CompleteMissionRequest)(nil),  // 3: rgb.ledger.v1.CompleteMissionRequest
	(*CompleteMissionResponse)(nil), // 4: rgb.ledger.v1.CompleteMissionResponse
	(*BalanceResponse)(nil),         // 5: rgb.ledger.v1.BalanceResponse
}
var file_api_proto_v1_game_proto_depIdxs = []int32{
	0, // 0: rgb.ledger.v1.MissionResponse.reward_color:type_name -> rgb.ledger.v1.RewardColor
	5, // 1: rgb.ledger.v1.CompleteMissionResponse.new_balance:type_name -> rgb.ledger.v1.BalanceResponse
	1, // 2: rgb.ledger.v1.GameService.RequestMission:input_type -> rgb.ledger.v1.RequestMissionRequest
	3, // 3: rgb.ledger.v1.GameService.CompleteMission:input_type -> rgb.ledger.v1.CompleteMissionRequest
	2, // 4: rgb.ledger.v1.GameService.RequestMission:output_type -> rgb.ledger.v1.MissionResponse
	4, // 5: rgb.ledger.v1.GameService.CompleteMission:output_type -> rgb.ledger.v1.CompleteMissionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_v1_game_proto_init() }
func file_api_proto_v1_game_proto_init() {
	if File_api_proto_v1_game_proto != nil {
		return
	}
	file_api_proto_v1_ledger_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_game_proto_rawDesc), len(file_api_proto_v1_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_game_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_game_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_game_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_game_proto_msgTypes,
	}.Build()
	File_api_proto_v1_game_proto = out.File
	file_api_proto_v1_game_proto_goTypes = nil
	file_api_proto_v1_game_proto_depIdxs = nil
}
