// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/proto/v1/ledger.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Red           uint32                 `protobuf:"varint,2,opt,name=red,proto3" json:"red,omitempty"`
	Green         uint32                 `protobuf:"varint,3,opt,name=green,proto3" json:"green,omitempty"`
	Blue          uint32                 `protobuf:"varint,4,opt,name=blue,proto3" json:"blue,omitempty"`
	Nonce         uint64                 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BalanceResponse) GetRed() uint32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *BalanceResponse) GetGreen() uint32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *BalanceResponse) GetBlue() uint32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

func (x *BalanceResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type SubmitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawPayload    []byte                 `protobuf:"bytes,1,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SenderPubKey  string                 `protobuf:"bytes,3,opt,name=sender_pub_key,json=senderPubKey,proto3" json:"sender_pub_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitTransactionRequest) GetRawPayload() []byte {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

func (x *SubmitTransactionRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SubmitTransactionRequest) GetSenderPubKey() string {
	if x != nil {
		return x.SenderPubKey
	}
	return ""
}

type TransactionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToAddress     string                 `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	AmountRed     uint32                 `protobuf:"varint,2,opt,name=amount_red,json=amountRed,proto3" json:"amount_red,omitempty"`
	AmountGreen   uint32                 `protobuf:"varint,3,opt,name=amount_green,json=amountGreen,proto3" json:"amount_green,omitempty"`
	AmountBlue    uint32                 `protobuf:"varint,4,opt,name=amount_blue,json=amountBlue,proto3" json:"amount_blue,omitempty"`
	Nonce         uint64                 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionPayload) Reset() {
	*x = TransactionPayload{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionPayload) ProtoMessage() {}

func (x *TransactionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionPayload.ProtoReflect.Descriptor instead.
func (*TransactionPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionPayload) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TransactionPayload) GetAmountRed() uint32 {
	if x != nil {
		return x.AmountRed
	}
	return 0
}

func (x *TransactionPayload) GetAmountGreen() uint32 {
	if x != nil {
		return x.AmountGreen
	}
	return 0
}

func (x *TransactionPayload) GetAmountBlue() uint32 {
	if x != nil {
		return x.AmountBlue
	}
	return 0
}

func (x *TransactionPayload) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TransactionPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SubmitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	NewBalance    *BalanceResponse       `protobuf:"bytes,4,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
	mi := &file_api_proto_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitTransactionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SubmitTransactionResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SubmitTransactionResponse) GetNewBalance() *BalanceResponse {
	if x != nil {
		return x.NewBalance
	}
	return nil
}

var File_api_proto_v1_ledger_proto protoreflect.FileDescriptor

const file_api_proto_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/ledger.proto\x12\rrgb.ledger.v1\"-\n" +
	"\x11GetBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"}\n" +
	"\x0fBalanceResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03red\x18\x02 \x01(\rR\x03red\x12\x14\n" +
	"\x05green\x18\x03 \x01(\rR\x05green\x12\x12\n" +
	"\x04blue\x18\x04 \x01(\rR\x04blue\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x04R\x05nonce\"\x7f\n" +
	"\x18SubmitTransactionRequest\x12\x1f\n" +
	"\vraw_payload\x18\x01 \x01(\fR\n" +
	"rawPayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12$\n" +
	"\x0esender_pub_key\x18\x03 \x01(\tR\fsenderPubKey\"\xca\x01\n" +
	"\x12TransactionPayload\x12\x1d\n" +
	"\n" +
	"to_address\x18\x01 \x01(\tR\ttoAddress\x12\x1d\n" +
	"\n" +
	"amount_red\x18\x02 \x01(\rR\tamountRed\x12!\n" +
	"\famount_green\x18\x03 \x01(\rR\vamountGreen\x12\x1f\n" +
	"\vamount_blue\x18\x04 \x01(\rR\n" +
	"amountBlue\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x04R\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xb4\x01\n" +
	"\x19SubmitTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12?\n" +
	"\vnew_balance\x18\x04 \x01(\v2\x1e.rgb.ledger.v1.BalanceResponseR\n" +
	"newBalance2\xcb\x01\n" +
	"\rLedgerService\x12P\n" +
	"\n" +
	"GetBalance\x12 .rgb.ledger.v1.GetBalanceRequest\x1a\x1e.rgb.ledger.v1.BalanceResponse\"\x00\x12h\n" +
	"\x11SubmitTransaction\x12'.rgb.ledger.v1.SubmitTransactionRequest\x1a(.rgb.ledger.v1.SubmitTransactionResponse\"\x00B\bZ\x06pkg/pbb\x06proto3"

var (
	file_api_proto_v1_ledger_proto_rawDescOnce sync.Once
	file_api_proto_v1_ledger_proto_rawDescData []byte
)

func file_api_proto_v1_ledger_proto_rawDescGZIP() []byte {
	file_api_proto_v1_ledger_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_ledger_proto_rawDesc), len(file_api_proto_v1_ledger_proto_rawDesc)))
	})
	return file_api_proto_v1_ledger_proto_rawDescData
}

var file_api_proto_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_v1_ledger_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),         // 0: rgb.ledger.v1.GetBalanceRequest
	(*BalanceResponse)(nil),           // 1: rgb.ledger.v1.BalanceResponse
	(*SubmitTransactionRequest)(nil),  // 2: rgb.ledger.v1.SubmitTransactionRequest
	(*TransactionPayload)(nil),        // 3: rgb.ledger.v1.TransactionPayload
	(*SubmitTransactionResponse)(nil), // 4: rgb.ledger.v1.SubmitTransactionResponse
}
var file_api_proto_v1_ledger_proto_depIdxs = []int32{
	1, // 0: rgb.ledger.v1.SubmitTransactionResponse.new_balance:type_name -> rgb.ledger.v1.BalanceResponse
	0, // 1: rgb.ledger.v1.LedgerService.GetBalance:input_type -> rgb.ledger.v1.GetBalanceRequest
	2, // 2: rgb.ledger.v1.LedgerService.SubmitTransaction:input_type -> rgb.ledger.v1.SubmitTransactionRequest
	1, // 3: rgb.ledger.v1.LedgerService.GetBalance:output_type -> rgb.ledger.v1.BalanceResponse
	4, // 4: rgb.ledger.v1.LedgerService.SubmitTransaction:output_type -> rgb.ledger.v1.SubmitTransactionResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_ledger_proto_init() }
func file_api_proto_v1_ledger_proto_init() {
	if File_api_proto_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_ledger_proto_rawDesc), len(file_api_proto_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_ledger_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_ledger_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_ledger_proto_msgTypes,
	}.Build()
	File_api_proto_v1_ledger_proto = out.File
	file_api_proto_v1_ledger_proto_goTypes = nil
	file_api_proto_v1_ledger_proto_depIdxs = nil
}
